In [1]:
print("Hello World")

Hello World


### Array Operation

In [2]:
import numpy as np

In [3]:
num = np.array([56,22,34,87,19,52,53,27])

In [4]:
print(num)

[56 22 34 87 19 52 53 27]


In [5]:
num

array([56, 22, 34, 87, 19, 52, 53, 27])

In [6]:
num[3] = 64
num

array([56, 22, 34, 64, 19, 52, 53, 27])

In [7]:
num[2:6]

array([34, 64, 19, 52])

In [8]:
num.dtype

dtype('int32')

In [9]:
num.size

8

In [10]:
num.shape

(8,)

In [11]:
num = np.array([56,22,34,87,19.23,52,53,27])

In [12]:
num

array([56.  , 22.  , 34.  , 87.  , 19.23, 52.  , 53.  , 27.  ])

In [13]:
num[1]

22.0

In [14]:
num.dtype

dtype('float64')

In [15]:
num = np.array([56,22,34,87,19,'Hello',53,27])

In [16]:
num

array(['56', '22', '34', '87', '19', 'Hello', '53', '27'], dtype='<U11')

In [17]:
ord("a")

97

In [19]:
chr(69)

'E'

In [26]:
city = np.array(['पुणे ','मुंबई','नागपूर ','नाशिक'])

In [27]:
city

array(['पुणे ', 'मुंबई', 'नागपूर ', 'नाशिक'], dtype='<U7')

In [28]:
city[3]

'नाशिक'

In [29]:
city[0]*10

'पुणे पुणे पुणे पुणे पुणे पुणे पुणे पुणे पुणे पुणे '

In [30]:
city[0].startswith('प')

True

In [37]:
x = [56,22,34,87,19.23,52,53,27]

In [36]:
x

[56, 22, 34, 87, 19.23, 52, 53, 27]

In [48]:
num = np.array([56,22,34,87,19.23,52,53,27])

In [34]:
x * 2

[56, 22, 34, 87, 19.23, 52, 53, 27, 56, 22, 34, 87, 19.23, 52, 53, 27]

In [43]:
num

array([56.  , 22.  , 34.  , 87.  , 19.23, 52.  , 53.  , 27.  ])

In [42]:
num * 2

array([112.  ,  44.  ,  68.  , 174.  ,  38.46, 104.  , 106.  ,  54.  ])

In [45]:
num - 10

array([46.  , 12.  , 24.  , 77.  ,  9.23, 42.  , 43.  , 17.  ])

In [46]:
num / 10

array([5.6  , 2.2  , 3.4  , 8.7  , 1.923, 5.2  , 5.3  , 2.7  ])

In [47]:
num > 40

array([ True, False, False,  True, False,  True,  True, False])

In [49]:
57 not in num

True

In [50]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [56]:
list(range(2,15,3))

[2, 5, 8, 11, 14]

In [57]:
list(range(20,2,-2))

[20, 18, 16, 14, 12, 10, 8, 6, 4]

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [60]:
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [61]:
np.arange(20,5,-2)

array([20, 18, 16, 14, 12, 10,  8,  6])

In [63]:
np.arange(1,10,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [66]:
num.all()

True

In [67]:
num.max()

87.0

In [68]:
num.argmax()

3

In [69]:
num.mean()

43.77875

In [70]:
num.sort()

In [71]:
num

array([19.23, 22.  , 27.  , 34.  , 52.  , 53.  , 56.  , 87.  ])

In [72]:
np.linspace(1,10,12)

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [73]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [74]:
x = np.array([[1,3,6,5],[6,9,8,0],[2,1,4,3]])

In [75]:
x

array([[1, 3, 6, 5],
       [6, 9, 8, 0],
       [2, 1, 4, 3]])

In [76]:
x.shape

(3, 4)

In [77]:
x.size

12

In [78]:
x[1][2]

8

In [80]:
x.reshape(6,2)

array([[1, 3],
       [6, 5],
       [6, 9],
       [8, 0],
       [2, 1],
       [4, 3]])

In [85]:
x.reshape(-1,2)

array([[1, 3],
       [6, 5],
       [6, 9],
       [8, 0],
       [2, 1],
       [4, 3]])

In [86]:
x.reshape(4,-1)

array([[1, 3, 6],
       [5, 6, 9],
       [8, 0, 2],
       [1, 4, 3]])

In [87]:
x.flatten()

array([1, 3, 6, 5, 6, 9, 8, 0, 2, 1, 4, 3])

### Series Operations

In [92]:
import pandas as pd

In [93]:
s = pd.Series([56,11,28,54,28,53,49])

In [94]:
s

0    56
1    11
2    28
3    54
4    28
5    53
6    49
dtype: int64

In [95]:
type(s)

pandas.core.series.Series

In [96]:
s.dtype

dtype('int64')

In [97]:
s.size

7

In [98]:
s = pd.Series([56,11,28,54,28,53,49], index=range(100,107))

In [99]:
s

100    56
101    11
102    28
103    54
104    28
105    53
106    49
dtype: int64

In [100]:
s[106]

49

### Data Frame!

In [101]:
x = pd.Series([1,2,3,4,5])
y = pd.Series(['Laxman','Pramod','Swapna','Anita'])
z = pd.Series([56.78, 76.34, 68.12, 65.34, 70.23])

In [103]:
df = pd.DataFrame({
    'Roll':x,
    'Name':y,
    'Marks':z
})

In [104]:
df

Roll    Name  Marks
0     1  Laxman  56.78
1     2  Pramod  76.34
2     3  Swapna  68.12
3     4   Anita  65.34
4     5     NaN  70.23

In [105]:
df.shape

(5, 3)

In [106]:
df.size

15

In [108]:
df.ndim

2

In [109]:
df.columns

Index(['Roll', 'Name', 'Marks'], dtype='object')

In [111]:
df.T

0       1       2      3      4
Roll        1       2       3      4      5
Name   Laxman  Pramod  Swapna  Anita    NaN
Marks   56.78   76.34   68.12  65.34  70.23

In [115]:
import os

In [116]:
os.getcwd()

'C:\\Users\\hp'